columnSuffix: null
contentColumnType: string
fieldGroup: 9265d2f0-4fa5-4187-8ee4-b6eb8808e295 # Pages
handle: colorsSwatches
instructions: 'Pick the color combination to use for the page theme'
name: 'Colors Swatches'
searchable: false
settings:
  contentTable: '{{%matrixcontent_colorsswatches}}'
  inputTemplatePath: site-module/_components/matrixfacades/colorswatches/input
  maxBlocks: ''
  minBlocks: ''
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: modules\sitemodule\fields\MatrixFacade
