columnSuffix: exqbhllc
contentColumnType: string
fieldGroup: 1aeaf5aa-fe37-42b5-aef9-f4556b92c43a # User
handle: disableMatrixFacades
instructions: ''
name: 'Disable Matrix Facades'
searchable: false
settings:
  multi: true
  options:
    -
      __assoc__:
        -
          - label
          - 'Disable Matrix Facades'
        -
          - value
          - disableMatrixFacades
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Checkboxes
