columnSuffix: rsfzwrwz
contentColumnType: 'decimal(12,2)'
fieldGroup: 86e92ff9-5119-4b99-b222-f3279dcc7818 # Flavors
handle: flavorPrice
instructions: ''
name: 'Flavor Price'
searchable: false
settings:
  decimals: '2'
  defaultValue: null
  max: null
  min: 0
  prefix: null
  previewCurrency: ''
  previewFormat: decimal
  size: null
  suffix: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Number
