columnSuffix: null
contentColumnType: string
fieldGroup: 92425d88-9e0a-4213-b474-f553f37261c2 # Orders
handle: scoops
instructions: ''
name: Scoops
searchable: false
settings:
  contentTable: '{{%matrixcontent_scoops}}'
  inputTemplatePath: site-module/_components/matrixfacades/scoops/input
  maxBlocks: ''
  minBlocks: ''
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: modules\sitemodule\fields\MatrixFacade
